# Configuration file

##########################################################################################################
# blocks
#--------------------------------------------------------------------------------------------------------#
# Use this section to convert registry name for blocks.
##########################################################################################################

blocks {
    S:"minecraft:air"=WarpDrive:blockAir WarpDrive:blockShipController WarpDrive:airBlock WarpDrive:protocolBlock
    S:"warpdrive:accelerator_control_point"=WarpDrive:blockAcceleratorControlPoint
    S:"warpdrive:accelerator_core"=WarpDrive:blockAcceleratorController
    S:"warpdrive:air_flow"=WarpDrive:blockAirFlow
    S:"warpdrive:air_generator.advanced"=WarpDrive:blockAirGenerator1 WarpDrive:blockAirGenerator WarpDrive:airgenBlock
    S:"warpdrive:air_generator.basic"=WarpDrive:blockAirGenerator2
    S:"warpdrive:air_generator.superior"=WarpDrive:blockAirGenerator3
    S:"warpdrive:air_shield"=WarpDrive:blockAirShield
    S:"warpdrive:air_source"=WarpDrive:blockAirSource
    S:"warpdrive:bedrock_glass"=WarpDrive:blockBedrockGlass
    S:"warpdrive:camera"=WarpDrive:blockCamera WarpDrive:cameraBlock
    S:"warpdrive:capacitor.advanced"=WarpDrive:blockEnergyBank@2
    S:"warpdrive:capacitor.basic"=WarpDrive:blockEnergyBank@1 WarpDrive:powerStore
    S:"warpdrive:capacitor.creative"=WarpDrive:blockEnergyBank@0
    S:"warpdrive:capacitor.superior"=WarpDrive:blockEnergyBank@3
    S:"warpdrive:chiller.advanced"=WarpDrive:blockChiller2
    S:"warpdrive:chiller.basic"=WarpDrive:blockChiller1
    S:"warpdrive:chiller.superior"=WarpDrive:blockChiller3
    S:"warpdrive:chunk_loader.advanced"=
    S:"warpdrive:chunk_loader.basic"=WarpDrive:blockChunkLoader WarpDrive:chunkLoader
    S:"warpdrive:chunk_loader.superior"=
    S:"warpdrive:cloaking_coil"=WarpDrive:blockCloakingCoil WarpDrive:cloakCoilBlock
    S:"warpdrive:cloaking_core"=WarpDrive:blockCloakingCore WarpDrive:cloakBlock
    S:"warpdrive:decorative"=WarpDrive:blockDecorative WarpDrive:decorative
    S:"warpdrive:electromagnet.advanced.glass"=WarpDrive:blockElectromagnetGlass2
    S:"warpdrive:electromagnet.advanced.plain"=WarpDrive:blockElectromagnetPlain2
    S:"warpdrive:electromagnet.basic.glass"=WarpDrive:blockElectromagnetGlass1
    S:"warpdrive:electromagnet.basic.plain"=WarpDrive:blockElectromagnetPlain1
    S:"warpdrive:electromagnet.superior.glass"=WarpDrive:blockElectromagnetGlass3
    S:"warpdrive:electromagnet.superior.plain"=WarpDrive:blockElectromagnetPlain3
    S:"warpdrive:enan_reactor_core.advanced"=
    S:"warpdrive:enan_reactor_core.basic"=WarpDrive:blockEnanReactorCore WarpDrive:powerReactor
    S:"warpdrive:enan_reactor_core.superior"=
    S:"warpdrive:enan_reactor_laser"=WarpDrive:blockEnanReactorLaser WarpDrive:powerLaser
    S:"warpdrive:force_field.advanced"=WarpDrive:blockForceField2
    S:"warpdrive:force_field.basic"=WarpDrive:blockForceField1
    S:"warpdrive:force_field.superior"=WarpDrive:blockForceField3
    S:"warpdrive:force_field_relay.advanced"=WarpDrive:blockForceFieldRelay2
    S:"warpdrive:force_field_relay.basic"=WarpDrive:blockForceFieldRelay1
    S:"warpdrive:force_field_relay.superior"=WarpDrive:blockForceFieldRelay3
    S:"warpdrive:gas"=WarpDrive:blockGas WarpDrive:gasBlock
    S:"warpdrive:highly_advanced_machine"=WarpDrive:blockHighlyAdvancedMachine WarpDrive:blockHAMachine
    S:"warpdrive:hull.advanced.glass"=WarpDrive:blockHull2_glass
    S:"warpdrive:hull.advanced.omnipanel"=WarpDrive:blockHull2_omnipanel
    S:"warpdrive:hull.advanced.plain"=WarpDrive:blockHull2_plain
    S:"warpdrive:hull.advanced.slab_black"=WarpDrive:blockHull2_slab_black
    S:"warpdrive:hull.advanced.slab_blue"=WarpDrive:blockHull2_slab_blue
    S:"warpdrive:hull.advanced.slab_brown"=WarpDrive:blockHull2_slab_brown
    S:"warpdrive:hull.advanced.slab_cyan"=WarpDrive:blockHull2_slab_cyan
    S:"warpdrive:hull.advanced.slab_gray"=WarpDrive:blockHull2_slab_gray
    S:"warpdrive:hull.advanced.slab_green"=WarpDrive:blockHull2_slab_green
    S:"warpdrive:hull.advanced.slab_light_blue"=WarpDrive:blockHull2_slab_lightBlue
    S:"warpdrive:hull.advanced.slab_lime"=WarpDrive:blockHull2_slab_lime
    S:"warpdrive:hull.advanced.slab_magenta"=WarpDrive:blockHull2_slab_magenta
    S:"warpdrive:hull.advanced.slab_orange"=WarpDrive:blockHull2_slab_orange
    S:"warpdrive:hull.advanced.slab_pink"=WarpDrive:blockHull2_slab_pink
    S:"warpdrive:hull.advanced.slab_purple"=WarpDrive:blockHull2_slab_purple
    S:"warpdrive:hull.advanced.slab_red"=WarpDrive:blockHull2_slab_red
    S:"warpdrive:hull.advanced.slab_silver"=WarpDrive:blockHull2_slab_silver
    S:"warpdrive:hull.advanced.slab_white"=WarpDrive:blockHull2_slab_white
    S:"warpdrive:hull.advanced.slab_yellow"=WarpDrive:blockHull2_slab_yellow
    S:"warpdrive:hull.advanced.stairs_black"=WarpDrive:blockHull2_stairs_black
    S:"warpdrive:hull.advanced.stairs_blue"=WarpDrive:blockHull2_stairs_blue
    S:"warpdrive:hull.advanced.stairs_brown"=WarpDrive:blockHull2_stairs_brown
    S:"warpdrive:hull.advanced.stairs_cyan"=WarpDrive:blockHull2_stairs_cyan
    S:"warpdrive:hull.advanced.stairs_gray"=WarpDrive:blockHull2_stairs_gray
    S:"warpdrive:hull.advanced.stairs_green"=WarpDrive:blockHull2_stairs_green
    S:"warpdrive:hull.advanced.stairs_light_blue"=WarpDrive:blockHull2_stairs_lightBlue
    S:"warpdrive:hull.advanced.stairs_lime"=WarpDrive:blockHull2_stairs_lime
    S:"warpdrive:hull.advanced.stairs_magenta"=WarpDrive:blockHull2_stairs_magenta
    S:"warpdrive:hull.advanced.stairs_orange"=WarpDrive:blockHull2_stairs_orange
    S:"warpdrive:hull.advanced.stairs_pink"=WarpDrive:blockHull2_stairs_pink
    S:"warpdrive:hull.advanced.stairs_purple"=WarpDrive:blockHull2_stairs_purple
    S:"warpdrive:hull.advanced.stairs_red"=WarpDrive:blockHull2_stairs_red
    S:"warpdrive:hull.advanced.stairs_silver"=WarpDrive:blockHull2_stairs_silver
    S:"warpdrive:hull.advanced.stairs_white"=WarpDrive:blockHull2_stairs_white
    S:"warpdrive:hull.advanced.stairs_yellow"=WarpDrive:blockHull2_stairs_yellow
    S:"warpdrive:hull.advanced.tiled"=WarpDrive:blockHull2_tiled
    S:"warpdrive:hull.basic.glass"=WarpDrive:blockHull1_glass
    S:"warpdrive:hull.basic.omnipanel"=WarpDrive:blockHull1_omnipanel
    S:"warpdrive:hull.basic.plain"=WarpDrive:blockHull1_plain
    S:"warpdrive:hull.basic.slab_black"=WarpDrive:blockHull1_slab_black
    S:"warpdrive:hull.basic.slab_blue"=WarpDrive:blockHull1_slab_blue
    S:"warpdrive:hull.basic.slab_brown"=WarpDrive:blockHull1_slab_brown
    S:"warpdrive:hull.basic.slab_cyan"=WarpDrive:blockHull1_slab_cyan
    S:"warpdrive:hull.basic.slab_gray"=WarpDrive:blockHull1_slab_gray
    S:"warpdrive:hull.basic.slab_green"=WarpDrive:blockHull1_slab_green
    S:"warpdrive:hull.basic.slab_light_blue"=WarpDrive:blockHull1_slab_lightBlue
    S:"warpdrive:hull.basic.slab_lime"=WarpDrive:blockHull1_slab_lime
    S:"warpdrive:hull.basic.slab_magenta"=WarpDrive:blockHull1_slab_magenta
    S:"warpdrive:hull.basic.slab_orange"=WarpDrive:blockHull1_slab_orange
    S:"warpdrive:hull.basic.slab_pink"=WarpDrive:blockHull1_slab_pink
    S:"warpdrive:hull.basic.slab_purple"=WarpDrive:blockHull1_slab_purple
    S:"warpdrive:hull.basic.slab_red"=WarpDrive:blockHull1_slab_red
    S:"warpdrive:hull.basic.slab_silver"=WarpDrive:blockHull1_slab_silver
    S:"warpdrive:hull.basic.slab_white"=WarpDrive:blockHull1_slab_white
    S:"warpdrive:hull.basic.slab_yellow"=WarpDrive:blockHull1_slab_yellow
    S:"warpdrive:hull.basic.stairs_black"=WarpDrive:blockHull1_stairs_black
    S:"warpdrive:hull.basic.stairs_blue"=WarpDrive:blockHull1_stairs_blue
    S:"warpdrive:hull.basic.stairs_brown"=WarpDrive:blockHull1_stairs_brown
    S:"warpdrive:hull.basic.stairs_cyan"=WarpDrive:blockHull1_stairs_cyan
    S:"warpdrive:hull.basic.stairs_gray"=WarpDrive:blockHull1_stairs_gray
    S:"warpdrive:hull.basic.stairs_green"=WarpDrive:blockHull1_stairs_green
    S:"warpdrive:hull.basic.stairs_light_blue"=WarpDrive:blockHull1_stairs_lightBlue
    S:"warpdrive:hull.basic.stairs_lime"=WarpDrive:blockHull1_stairs_lime
    S:"warpdrive:hull.basic.stairs_magenta"=WarpDrive:blockHull1_stairs_magenta
    S:"warpdrive:hull.basic.stairs_orange"=WarpDrive:blockHull1_stairs_orange
    S:"warpdrive:hull.basic.stairs_pink"=WarpDrive:blockHull1_stairs_pink
    S:"warpdrive:hull.basic.stairs_purple"=WarpDrive:blockHull1_stairs_purple
    S:"warpdrive:hull.basic.stairs_red"=WarpDrive:blockHull1_stairs_red
    S:"warpdrive:hull.basic.stairs_silver"=WarpDrive:blockHull1_stairs_silver
    S:"warpdrive:hull.basic.stairs_white"=WarpDrive:blockHull1_stairs_white
    S:"warpdrive:hull.basic.stairs_yellow"=WarpDrive:blockHull1_stairs_yellow
    S:"warpdrive:hull.basic.tiled"=WarpDrive:blockHull1_tiled
    S:"warpdrive:hull.superior.glass"=WarpDrive:blockHull3_glass
    S:"warpdrive:hull.superior.omnipanel"=WarpDrive:blockHull3_omnipanel
    S:"warpdrive:hull.superior.plain"=WarpDrive:blockHull3_plain
    S:"warpdrive:hull.superior.slab_black"=WarpDrive:blockHull3_slab_black
    S:"warpdrive:hull.superior.slab_blue"=WarpDrive:blockHull3_slab_blue
    S:"warpdrive:hull.superior.slab_brown"=WarpDrive:blockHull3_slab_brown
    S:"warpdrive:hull.superior.slab_cyan"=WarpDrive:blockHull3_slab_cyan
    S:"warpdrive:hull.superior.slab_gray"=WarpDrive:blockHull3_slab_gray
    S:"warpdrive:hull.superior.slab_green"=WarpDrive:blockHull3_slab_green
    S:"warpdrive:hull.superior.slab_light_blue"=WarpDrive:blockHull3_slab_lightBlue
    S:"warpdrive:hull.superior.slab_lime"=WarpDrive:blockHull3_slab_lime
    S:"warpdrive:hull.superior.slab_magenta"=WarpDrive:blockHull3_slab_magenta
    S:"warpdrive:hull.superior.slab_orange"=WarpDrive:blockHull3_slab_orange
    S:"warpdrive:hull.superior.slab_pink"=WarpDrive:blockHull3_slab_pink
    S:"warpdrive:hull.superior.slab_purple"=WarpDrive:blockHull3_slab_purple
    S:"warpdrive:hull.superior.slab_red"=WarpDrive:blockHull3_slab_red
    S:"warpdrive:hull.superior.slab_silver"=WarpDrive:blockHull3_slab_silver
    S:"warpdrive:hull.superior.slab_white"=WarpDrive:blockHull3_slab_white
    S:"warpdrive:hull.superior.slab_yellow"=WarpDrive:blockHull3_slab_yellow
    S:"warpdrive:hull.superior.stairs_black"=WarpDrive:blockHull3_stairs_black
    S:"warpdrive:hull.superior.stairs_blue"=WarpDrive:blockHull3_stairs_blue
    S:"warpdrive:hull.superior.stairs_brown"=WarpDrive:blockHull3_stairs_brown
    S:"warpdrive:hull.superior.stairs_cyan"=WarpDrive:blockHull3_stairs_cyan
    S:"warpdrive:hull.superior.stairs_gray"=WarpDrive:blockHull3_stairs_gray
    S:"warpdrive:hull.superior.stairs_green"=WarpDrive:blockHull3_stairs_green
    S:"warpdrive:hull.superior.stairs_light_blue"=WarpDrive:blockHull3_stairs_lightBlue
    S:"warpdrive:hull.superior.stairs_lime"=WarpDrive:blockHull3_stairs_lime
    S:"warpdrive:hull.superior.stairs_magenta"=WarpDrive:blockHull3_stairs_magenta
    S:"warpdrive:hull.superior.stairs_orange"=WarpDrive:blockHull3_stairs_orange
    S:"warpdrive:hull.superior.stairs_pink"=WarpDrive:blockHull3_stairs_pink
    S:"warpdrive:hull.superior.stairs_purple"=WarpDrive:blockHull3_stairs_purple
    S:"warpdrive:hull.superior.stairs_red"=WarpDrive:blockHull3_stairs_red
    S:"warpdrive:hull.superior.stairs_silver"=WarpDrive:blockHull3_stairs_silver
    S:"warpdrive:hull.superior.stairs_white"=WarpDrive:blockHull3_stairs_white
    S:"warpdrive:hull.superior.stairs_yellow"=WarpDrive:blockHull3_stairs_yellow
    S:"warpdrive:hull.superior.tiled"=WarpDrive:blockHull3_tiled
    S:"warpdrive:ic2_reactor_laser_cooler"=WarpDrive:blockIC2reactorLaserMonitor WarpDrive:reactorMonitor
    S:"warpdrive:iridium_block"=WarpDrive:blockIridium WarpDrive:iridiumBlock
    S:"warpdrive:lamp_bubble"=
    S:"warpdrive:lamp_flat"=
    S:"warpdrive:lamp_long"=
    S:"warpdrive:laser"=WarpDrive:blockLaser WarpDrive:laserBlock
    S:"warpdrive:laser_camera"=WarpDrive:blockLaserCamera WarpDrive:laserCamBlock
    S:"warpdrive:laser_medium.advanced"=
    S:"warpdrive:laser_medium.basic"=
    S:"warpdrive:laser_medium.superior"=WarpDrive:blockLaserMedium WarpDrive:boosterBlock
    S:"warpdrive:laser_tree_farm"=WarpDrive:blockLaserTreeFarm WarpDrive:laserTreeFarmBlock
    S:"warpdrive:lift"=WarpDrive:blockLift WarpDrive:liftBlock
    S:"warpdrive:mining_laser"=WarpDrive:blockMiningLaser WarpDrive:miningLaserBlock
    S:"warpdrive:monitor"=WarpDrive:blockMonitor WarpDrive:monitorBlock
    S:"warpdrive:particles_collider"=WarpDrive:blockParticlesCollider
    S:"warpdrive:particles_injector"=WarpDrive:blockParticlesInjector
    S:"warpdrive:projector.advanced"=
    S:"warpdrive:projector.basic"=
    S:"warpdrive:projector.superior"=
    S:"warpdrive:radar"=WarpDrive:blockRadar WarpDrive:radarBlock
    S:"warpdrive:security_station"=
    S:"warpdrive:ship_controller.advanced"=WarpDrive:blockProjector2
    S:"warpdrive:ship_controller.basic"=WarpDrive:blockProjector1
    S:"warpdrive:ship_controller.superior"=WarpDrive:blockProjector3
    S:"warpdrive:ship_core.advanced"=
    S:"warpdrive:ship_core.basic"=WarpDrive:blockShipCore WarpDrive:warpCore
    S:"warpdrive:ship_core.superior"=
    S:"warpdrive:ship_scanner.advanced"=
    S:"warpdrive:ship_scanner.basic"=WarpDrive:blockShipScanner WarpDrive:scannerBlock
    S:"warpdrive:ship_scanner.superior"=
    S:"warpdrive:siren_industrial.advanced"=
    S:"warpdrive:siren_industrial.basic"=WarpDrive:siren@0
    S:"warpdrive:siren_industrial.superior"=
    S:"warpdrive:siren_military.advanced"=WarpDrive:siren@5
    S:"warpdrive:siren_military.basic"=WarpDrive:siren@4
    S:"warpdrive:siren_military.superior"=WarpDrive:siren@6
    S:"warpdrive:transporter_beacon"=WarpDrive:blockTransporterBeacon WarpDrive:blockTransportBeacon WarpDrive:transportBeacon
    S:"warpdrive:transporter_containment"=WarpDrive:blockTransporterContainment
    S:"warpdrive:transporter_core"=WarpDrive:blockTransporterCore WarpDrive:blockTransporter WarpDrive:transporter
    S:"warpdrive:transporter_scanner"=WarpDrive:blockTransporterScanner
    S:"warpdrive:void_shell.glass"=WarpDrive:blockVoidShellGlass
    S:"warpdrive:void_shell.plain"=WarpDrive:blockVoidShellPlain
    S:"warpdrive:warp_isolation"=WarpDrive:blockWarpIsolation WarpDrive:isolationBlock
    S:"warpdrive:weapon_controller"=WarpDrive:blockWeaponController
}


